### ISSUE TITLE
DDA quant module: Precursor vs peptidoform

### ISSUE THREAD

**Issue by RalfG** [Proteobench/ProteoBench#114]
The module is ion centric, so it should ideally parse the sequence + modifications + charge as a quantifiable entry. Currently it seems that the parser treats sequence + charge as an entity: 
https://github.com/Proteobench/ProteoBench/blob/main/proteobench/modules/dda_quant/parse.py

**Comment by RobbinBouwmeester** [comment]
Conclusion is that ions should indeed contain modifications.

**Comment by RobbinBouwmeester** [comment]
Started looking into this, intercomparison of files is not an issue. We can easily add that by merging the modification string to the sequence or already taking the modified sequence.

However since we want to store intermediate (and even raw files) to do a further comparison we might want to store them with a universal sequence+modification string (such as proforma) this might require additional work.

I have done something for MQ with psm_utils: #132

**Comment by RobbinBouwmeester** [comment]
Fully done since #137
