### ISSUE TITLE
Remove the Proline runs (I did not upload the right ones)

### ISSUE THREAD

**Issue by mlocardpaulet** [Proteobench/ProteoBench#228]
The two proline points: Proline__20240122_190626 and Proline__20240122_190958 are not valid. I did not upload the correct ones. So I want to remove them from the set of public runs and here are my questions:
1. I can remove the corresponding lines in the file `results.json` of the module repo: easy!
2. What do we do about the corresponding files in @julianu repo? (I mean the param and input csvs)
3. what else do I miss? 

Please let me know, I am happy to delete the lines in `results.json` as soon as you give me the green light. And then we will upload a lot more Proline runs with different parameters etc...

**Comment by enryH** [comment]
So you would delete if from the [results repository](https://github.com/Proteobench/Results_Module2_quant_DDA/blob/main/results.json)? I think it would be good if we create a command to delete if from that json, so that formatting errors are avoided. This should be a simple deletion of a key in a dictionary.

**Comment by julianu** [comment]
I just need the hash-codes of the datasets you would like to remove. Best pm them to me, as soon as the json is updated.
Otherwise, they would just take up some space on the drive, which is also not too much a problem right now.
Or should we keep them as an archive somewhere? But probably not necessary, if they are just wrong.

**Comment by mlocardpaulet** [comment]
> So you would delete if from the [results repository](https://github.com/Proteobench/Results_Module2_quant_DDA/blob/main/results.json)? I think it would be good if we create a command to delete if from that json, so that formatting errors are avoided. This should be a simple deletion of a key in a dictionary.

that was my plan: to delete the corresponding lines. You make a good point, up to you: shall I delete or do you want to create the command? Not sure exactly how you would want to do that. Or option 3: I delete the 2 data sets for know and we work on a command for the next ones?

**Comment by enryH** [comment]
I'll create a PR in 5mins...

**Comment by enryH** [comment]
So dumping the json via pandas is different from the built-in json function per default. Can probably be fixed, but pandas as a dependency is not a big issue.

**Comment by enryH** [comment]
No, it's only in case there is a mistake. It's maintainer who can submit a PR to delete the points. @RobbinBouwmeester The repository is only for storage and only accessible to maintainers?
