### ISSUE TITLE
error during public submission of MQ data v2.5.1.0

### ISSUE THREAD

**Issue by mlocardpaulet** [Proteobench/ProteoBench#283]
**Describe the bug**
see screenshot below

**To Reproduce**
1. Upload MQ evidence file from v. 2.5.1.0
2. Click on 'Parse and bench'
3. Scroll down to public submission
4. upload corresponding mqpar.xml
5. check parsed parameters and confirm that metadata is correct
6. press 'I really want to upload it'
7. error (see screenshot below)

**Expected behavior**
there should have been falling balloonsm, and a PR sent to proteobot

**Screenshots**
![image](https://github.com/Proteobench/ProteoBench/assets/8386272/a5a93aa9-8e21-4677-9bbc-d31027f46691)

**Desktop (please complete the following information):**
 - OS: macOS Sonoma 14.2.1
 - Browser: Chrome Version 123.0.6312.122 (Official Build) (arm64)
 - done on the current server version

**Additional context**
I can send the two files (mqpar and evidence) to anyone interested

**Comment by enryH** [comment]
So the error specifies that it is `param_loc` is of type `list`. This is raised on the following line

https://github.com/Proteobench/ProteoBench/blob/f33006c666ed60d81658409c2c2fcf78364032d7/proteobench/modules/dda_quant_base/module.py#L204

`param_loc` is passed to the function. Going up the stack trace, I think the issue is that now the widget records a list of filenames instead of a single filename (which was needed to support FragPipe).

So the error is raised where the filename should be extracted. I think this will happen with any parameter file atm. I can try to give it a go.
