### ISSUE TITLE
issue with alphapept parameter parsing

### ISSUE THREAD

**Issue by mlocardpaulet** [Proteobench/ProteoBench#310]
**Describe the bug**
I have an error message when I upload the .yaml file from and alphapept file for public upload. Everything before this worked out well. 

**To Reproduce**
1. Parse and bench an alphapept `results_peptide.csv` output file
2. the plot loads nicely
3. Scroll down to public upload, and load the `.yaml` corresponding to the search (I also tried the `results.yaml` without success)
4. See error (screenshot below)

**Expected behavior**
the parameter files should be parsed for public uploac

**Screenshots**
![image](https://github.com/Proteobench/ProteoBench/assets/8386272/7ff91271-85f0-4cd8-b232-cf310d0aa9cc)

I can provide a zip with the associated files :)

**Comment by enryH** [comment]
It is not a parsing error directly, but an Error with the loading the file. It's probably a regression due to that i added for FragPipe the possibility to upload more than one file... If we are back to one configuration file to parse, we could revert that change... 

It could be that other tools are also affected. I'll provide a fix soon.
