### ISSUE TITLE
Merging documentation and description on website

### ISSUE THREAD

**Issue by RobbinBouwmeester** [Proteobench/ProteoBench#344]
There seems to be different information on the proteobench website and the documentation. To get all information you now would need to combine the two. It would be preferable to have all information on both sites.

**Comment by mlocardpaulet** [comment]
You would duplicate the information (have it on both sites)? Or would you keep it in the documentation and make a link?
I think that this is definitely an important point to work on next week.

**Comment by RobbinBouwmeester** [comment]
Either solution would work for me, but Ralf pointed out to me the current state might be confusing.

**Comment by mlocardpaulet** [comment]
I think that Ralf is right.

**Comment by mlocardpaulet** [comment]
**We decided not to change any of the content of the webinterface for the moment.**
it will have to be done at a later stage.
for now we changed the documentation only, so that it consists of a landing page with a description of ProteoBench and a description of each module with the links to the corresponding module to see the plot and/or to publicly submit data.
