### ISSUE TITLE
Start on the DIA module

### ISSUE THREAD

**Issue by RobbinBouwmeester** [Proteobench/ProteoBench#348]
We need:

- [x] Input data from different software tools (DIA-NN, Spectronaut, MSFragger DIA, AlphaDIA, Encyclopedia, MaxDIA...)
- [x] Agree on data we are going to use
- [x] Agree on metrics we are going to use

Dev side:
- [x] Make parsing of the tools work
- [x] Calculate metrics
- [x] Show plots
- [x] Webinterface
- [x] Submission GH

**Comment by brvpuyve** [comment]
@wolski and I have input data from different software tools (DIA-NN, Spectronaut and EncyclopeDIA). I have asked Julia from the Mann group to generate AlphaDIA output since I am encountering some issues. 
Dataset: Orbitrap dataset from LFQ benchmark dataset (https://www.nature.com/articles/s41597-022-01216-6) - 3x A_Alpha and 3xB_Alpha
