### ISSUE TITLE
Add Spectronaut support

### ISSUE THREAD

**Issue by brvpuyve** [Proteobench/ProteoBench#372]
=> Input files: https://cloud.cmb.ugent.be/index.php/s/zdGB3zZ7Fwed9gq?path=%2FModule_4_DIA_Quantification%2FSpectronaut 

In the parameter file no clear definition of MS1 and MS2 tolerance:
  │  ├─ MS1 Mass Tolerance Strategy:	System Default
   │  └─ MS2 Mass Tolerance Strategy:	System Default

**Comment by brvpuyve** [comment]
Can someone also help out with the documentation on Spectronaut? @wolski @AnStaes

**Comment by rodvrees** [comment]
@brvpuyve, none of the input files have species information. E.g. there's no columns with <gene_name>_HUMAN or <gene_name>_YEAST output, which is necessary.

**Comment by brvpuyve** [comment]
@rodvrees Witold reran the analysis with some changed parameter settings which should have resolved the loss of species information. The files have been uploaded to the Cloud server.

**Comment by rodvrees** [comment]
Spectronaut output parsing is now ready (#399). Instead of the user having to fiddle with settings to get assure the species information to be present, we've implemented a mapping step so that gene names get mapped to the correct protein descriptor.

e.g. Q8WWZ7 (in spectronaut output) will be mapped to sp|Q8WWZ7|ABCA5_HUMAN.

This will also apply for FraggerDIA output, which has the same issue

**Comment by brvpuyve** [comment]
Great, thanks Robbe!

**Comment by wolski** [comment]
Spectronaut support completed with PR #437
