### ISSUE TITLE
web interface reformatting: What tabs and what to put in each tab?

### ISSUE THREAD

**Issue by mlocardpaulet** [Proteobench/ProteoBench#412]
Here are my comments/suggestions for the new web interface of the modules. Feel free to disagree/comment on all these points :). I go tab by tab. 

Tab **“module description”**: I don’t think that we need it at all since everything that is currently there is also in the [documentation of the module](https://proteobench.readthedocs.io/en/latest/available-modules/2-DDA-Quantification-ion-level/). But we need a very visible link to the documentation (see checkbox below).

- [x] put a link to the documentation of the module (https://proteobench.readthedocs.io/en/latest/available-modules/2-DDA-Quantification-ion-level/) somewhere. Ideally, this link would be reachable from all the tabs?
- [x] and maybe add a link to the module in the documentation? I did not see it, I think that the link to the module itself is only on the landing page of the documentation. 

Tab **“Results (All Data)**: If we follow my first comment, this will be the landing tab, so we would directly see the public plot. 
- [x] I would call it “Public benchmark runs” (or to be in line with what is in our [glossary](https://proteobench.readthedocs.io/en/latest/general-information/1-glossary/) “Validated Benchmark runs”). I don’t know if we need to add a brief description.

Tab **“Submission form**”: 
- [x] maybe I would rename it “submit new data” and then label the following tab “visualise new data outputs”
- [x] I would remove the description and keep only from “Input files”. 
- [x] I would remove the sentence “Currently, we support output files from AlphaPept, i2MassChroQ, MaxQuant, FragPipe, Proline and Sage. It is also possible to reformat your data in a tab-delimited file that we call "custom format" in the [documentation](https://proteobench.readthedocs.io/en/stable/available-modules/2-DDA-Quantification-ion-level/#custom-format).” 

Tab **“in-depth submission”**:
- [ ] I would rename it “visualise new data outputs”, and I think that I would also add the general plot in this tab (the one that currently is in “Results (New submissions)”).
- [x] I would replace “Download calculated ratios” with “Download table”. Since it is just below the table, it is clear enough. And it contains more than just the ratios.

Tab **“Results (New submissions)**: 
- [ ] I would remove this tab altogether, and move the plot to the tab just before. 
- [x] I would add in the bottom a sentence about public submission: “If you want to make this point — and the associated data — publicly available, please go to “Public Submission”). 

Tab **“Public Submission”**: 
- [x] I would rename it “make your workflow output public”, but “Public submission” is also fine.

**Comment by RobbinBouwmeester** [comment]
- I think most of the names you suggest for tabs are too long. We need to think of one or two word descriptions for the tabs. Otherwise it is hard to fit the names on the tabs and shorter names are probably better anyway.
- I would keep a strict separation between the more in-depth plots and the main plot. These results are fundamentally different, putting so many things together goes against current philosphy of the tabs, and I do not think putting them together adds anything in terms of clarity
- I also removed this from the input submission field "Remember: contaminant sequences are already present in the fasta file associated to this module. **Do not add other contaminants** to your search. This is important when using MaxQuant and FragPipe, among other tools." 

All the other suggestions should be on main soon.

**Comment by RobbinBouwmeester** [comment]
Has been resolved.
