### ISSUE TITLE
cannot find the charge state in the "Sample of the processed file" returned in DDA quan

### ISSUE THREAD

**Issue by mlocardpaulet** [Proteobench/ProteoBench#77]
The counts should be at precursor level, right? So we should have the information of sequence + charge (+ modification I guess) in the table. Am I wrong?

**Comment by RobbinBouwmeester** [comment]
They are currently collapsed for different charge states, so they are at sequence + modification level. For the counts we can discuss if this is correct (I think it is), but for quantification they should definitely be collapsed as the ionization of (higher) charge states between runs is not really what we are testing. Otherwise this might screw up the ratios we expect to see.
