### ISSUE TITLE
Update search parameters of new data point with values from parsed meta data file before submission to proteobot

### ISSUE THREAD

**Issue by viikiid** [Proteobench/ProteoBench#98]
Currently the values that are submitted to the public repository are those that users entered in the additional parameters input boxes. As soon as the parsing of the metadatafile is done we will need to change that to the parameters parsed from the meta data file

**Comment by RobbinBouwmeester** [comment]
@viikiid can you confirm this has been resolved?

**Comment by scaramonche** [comment]
As far as I understood, this has not been resolved yet, since it is waiting for the parsed meta data to be available in the code.

**Comment by enryH** [comment]
So here metadata refers to the parsed parameters file #101 , e.g. `mqpar.xml` for MaxQuant.

**Comment by scaramonche** [comment]
There is a branch `use-metadata-params-for-submission`, where I started this. I have not finalized it because the next step would need to be a unification of the set of parameters and their names that we want to keep and provide on the website. One version is what we have as additional parameters on the website (as defined in `webinterface/dda_quant.json`) and the other version is the parameters extracted from the meta file and currently defined in `proteobench/params/__init__.py`. 
If I understood correctly, the ones Henry used (params init file) is what we agreed on, but I was not sure if the plan is to use exactly those for the website as well.

**Comment by enryH** [comment]
We agreed to select and use the names aligned with the SDRF-extended parameters. Some parameters which are needed for a task and are not defined by SDRF-extended will need to be added.  See #58 for previous discussion, especially the last comment: 
https://github.com/Proteobench/ProteoBench/issues/58#issuecomment-1782930610

**Comment by RobbinBouwmeester** [comment]
Fixed in #158
